### ISSUE TITLE
Logout Issue

### ISSUE THREAD

**Issue by farhanad007** [SpeedOut-Source/BlockLancer#11]
Summary : No Logout option

Description : If a user wants to logout after finishing work there is no logout option .

Step to task : 
1.Open the site'
2.Log in the user
3.Finishing work
4.Need to logout
5.No log out option found

Expected result : User should have found a log out option

Actual Outcome : User can not find a Logout option

Catagory : Critical
![Screenshot (62)](https://github.com/user-attachments/assets/b6cbca37-c94e-4aff-aa3e-39bbb302bcd6)

**Comment by arnob016** [comment]
You can logout/disconnect your wallet.

![image](https://github.com/user-attachments/assets/d3eb67a4-4e13-4ea1-bc68-69b9fcd7ebd7)
