### ISSUE TITLE
Rabet Login Not Working

### ISSUE THREAD

**Issue by Farabi87** [SpeedOut-Source/BlockLancer#16]
Steps to Reproduce:
Install the Rabet extension in the browser.
Create an account in Rabet.
Navigate to BlockLancer and select the Rabet login option.
Expected Behavior: The user should be able to successfully log in using the Rabet extension.
Actual Behavior: The login fails without any error message.
Device: Asus Rog Strix laptop
Browser: Chrome 
![Screenshot_2](https://github.com/user-attachments/assets/270af3c5-772c-4b15-a9bf-b9c2211252e7)

**Comment by arnob016** [comment]
Duplicate of an issue reported by same issuer .
